version: '3.8'

networks:
  default:
    name: movieapp-network
    external: true

services:  
  movieapp-frontend:
    container_name: movieapp-frontend
    build: .
    image: movieapp-frontend:latest
    networks:
      default:
    ports:
      - '3000:3000'
    restart: always