-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: mariadb
-- Generation Time: Jan 06, 2022 at 06:33 AM
-- Server version: 10.6.5-MariaDB
-- PHP Version: 7.4.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `movies`
--

-- --------------------------------------------------------

--
-- Table structure for table `favorites`
--

CREATE TABLE `favorites` (
  `favoriteId` int(11) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
  `movieId` int(11) NOT NULL,
  `userId` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `favorites`
--

INSERT INTO `favorites` (`favoriteId`, `timestamp`, `movieId`, `userId`) VALUES
(1, '2022-01-06 06:33:11', 508, 1);

-- --------------------------------------------------------

--
-- Table structure for table `movies`
--

CREATE TABLE `movies` (
  `movieId` int(11) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
  `title` varchar(256) NOT NULL,
  `release_date` date DEFAULT NULL,
  `backdrop_path` varchar(256) DEFAULT NULL,
  `overview` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `movies`
--

INSERT INTO `movies` (`movieId`, `timestamp`, `title`, `release_date`, `backdrop_path`, `overview`) VALUES
(508, '2022-01-06 06:02:05', 'Love Actually', '2003-09-07', '/xUWf5xX0AnZgAnYXAMk03zTbsef.jpg', '\'Love Actually\' follows the lives of eight very different couples dealing with their love lives, in various loosely and interrelated tales, all set during a frantic month before Christmas in London, England.'),
(603, '2022-01-06 06:02:05', 'The Matrix', '1999-03-30', '/ncEsesgOJDNrTUED89hYbA117wo.jpg', 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.'),
(627, '2022-01-06 06:02:04', 'Trainspotting', '1996-02-23', '/e9GbzPawXDFvLwSseCXpHkbCyAP.jpg', 'Heroin addict Mark Renton stumbles through bad ideas and sobriety attempts with his unreliable friends -- Sick Boy, Begbie, Spud and Tommy. He also has an underage girlfriend, Diane, along for the ride. After cleaning up and moving from Edinburgh to London, Mark finds he can\'t escape the life he left behind when Begbie shows up at his front door on the lam, and a scheming Sick Boy follows.'),
(1791, '2022-01-06 06:02:05', 'The Piano Teacher', '2001-07-21', '/f3QlognjrlLlJVHDJb1f0yLQxTL.jpg', 'Erika Kohut, a sexually repressed piano teacher living with her domineering mother, meets a young man who starts romantically pursuing her.'),
(2576, '2022-01-06 06:02:05', 'The Diary of Anne Frank', '1959-03-18', '/jVkLfnnPfR3GKjsY05utE8l8W0i.jpg', 'The true, harrowing story of a young Jewish girl who, with her family and their friends, is forced into hiding in an attic in Nazi-occupied Amsterdam.'),
(4935, '2022-01-06 06:02:05', 'Howl\'s Moving Castle', '2004-11-19', '/vwBa7djy1oxfxUjc7YtVgGNsjrT.jpg', 'When Sophie, a shy young woman, is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.'),
(11298, '2022-01-06 06:02:05', 'The Howling', '1981-01-21', '/7beih8MLbWkx8iRtIffBMi2bHZL.jpg', 'After a bizarre and near fatal encounter with a serial killer, a newswoman is sent to a rehabilitation center whose inhabitants may not be what they seem.'),
(83542, '2022-01-06 06:02:04', 'Cloud Atlas', '2012-10-26', '/2lw4O1QOnJIVYaLrVuQyjtjwOuN.jpg', 'A set of six nested stories spanning time between the 19th century and a distant post-apocalyptic future. Cloud Atlas explores how the actions and consequences of individual lives impact one another throughout the past, the present and the future. Action, mystery and romance weave through the story as one soul is shaped from a killer into a hero and a single act of kindness ripples across centuries to inspire a revolution in the distant future.  Based on the award winning novel by David Mitchell. Directed by Tom Tykwer and the Wachowskis.'),
(370172, '2022-01-06 06:02:05', 'No Time to Die', '2021-09-29', '/r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg', 'Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.'),
(400090, '2022-01-06 06:02:04', 'The Nightingale', '2018-09-23', '/7Cp11vte6kD5vlYMfrbD2MHvTak.jpg', 'In 1825, Clare, a 21-year-old Irish convict, chases a British soldier through the rugged Tasmanian wilderness, bent on revenge for a terrible act of violence he committed against her family. She enlists the services of an Aboriginal tracker who is also marked by trauma from his own violence-filled past.'),
(412656, '2022-01-06 06:02:04', 'Chaos Walking', '2021-02-24', '/ovggmAOu1IbPGTQE8lg4lBasNC7.jpg', 'Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.'),
(423333, '2022-01-06 06:02:04', 'Mass', '2021-10-08', '/cv6Nn8Yt9mgFoUSievEdW9JK82A.jpg', 'Years after a tragic shooting, the parents of both the victim and the perpetrator meet face-to-face.'),
(424277, '2022-01-06 06:02:05', 'Annette', '2021-07-06', '/cDVWsqsnGwIUqOSzAuDS0PIhNdW.jpg', 'The story of Henry, a stand-up comedian with a fierce sense of humour and Ann, a singer of international renown. In the spotlight, they are the perfect couple, healthy, happy, and glamourous. The birth of their first child, Annette, a mysterious girl with an exceptional destiny, will change their lives.'),
(425909, '2022-01-06 06:02:05', 'Ghostbusters: Afterlife', '2021-11-11', '/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg', 'When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.'),
(430155, '2022-01-06 06:02:05', 'Coma', '2019-11-19', '/8HbqSozBJxv6UldR9lMUECUlbLI.jpg', 'A young and talented architect comes to his senses after a horrific accident only to find himself in the odd dystopian world. A world that is filled with the memories of all current coma patients. Just like a human memory this world is fragmental, chaotic and unstable. This is COMA: icecaps, rivers and cities can all exist in a space of a single room and laws of physics are no longer laws as they can be bent.'),
(438631, '2022-01-06 06:02:05', 'Dune', '2021-09-15', '/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg', 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet\'s exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity\'s greatest potential-only those who can conquer their fear will survive.'),
(438695, '2022-01-06 06:02:05', 'Sing 2', '2021-12-01', '/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg', 'Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.'),
(451500, '2022-01-06 06:02:05', 'Christmas & Co.', '2017-12-06', '/uc369Ws3HHY4NXCgs2hwb5pjrGN.jpg', 'Christmas is on its way and with it disaster. The 92,000 responsible for manufacturing children\'s toys all become sick at the same time! It\'s a tough moment for Santa, better known as Father Christmas. He\'s left no choice: he must make an emergency trip to Earth with his reindeer to search for a remedy. When he arrives, he must find some allies to save the magic of Christmas.'),
(454527, '2022-01-06 06:02:05', 'Benedetta', '2021-07-09', '/voi88IfoNAykXAEd0zrnczNM8LF.jpg', 'A 17th-century nun becomes entangled in a forbidden lesbian affair with a novice. But it is Benedetta\'s shocking religious visions that threaten to shake the Church to its core.'),
(459151, '2022-01-06 06:02:05', 'The Boss Baby: Family Business', '2021-07-01', '/akwg1s7hV5ljeSYFfkw7hTHjVqk.jpg', 'The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.'),
(460458, '2022-01-06 06:02:05', 'Resident Evil: Welcome to Raccoon City', '2021-11-24', '/o76ZDm8PS9791XiuieNB93UZcRV.jpg', 'Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.'),
(476669, '2022-01-06 06:02:05', 'The King\'s Man', '2021-12-26', '/4OTYefcAlaShn6TGVK33UxLW9R7.jpg', 'As a collection of history\'s worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.'),
(482373, '2022-01-06 06:02:05', 'Don\'t Breathe 2', '2021-08-12', '/pUc51UUQb1lMLVVkDCaZVsCo37U.jpg', 'The Blind Man has been hiding out for several years in an isolated cabin and has taken in and raised a young girl orphaned from a devastating house fire. Their quiet life together is shattered when a group of criminals kidnap the girl, forcing the Blind Man to leave his safe haven to save her.'),
(501841, '2022-01-06 06:02:04', 'A Journal for Jordan', '2021-12-22', '/esbNsC8ugbzUoL1SDNhL00JmP4z.jpg', 'Based on the true story of First Sergeant Charles Monroe King, a soldier deployed to Iraq begins to keep a journal of love and advice for his infant son. Back at home, senior New York Times editor Dana Canedy revisits the story of her unlikely, life-altering relationship with King and his enduring devotion to her and their child.'),
(511809, '2022-01-06 06:02:05', 'West Side Story', '2021-12-08', '/r4VQbiydjDH7ULo1HWjkkrNt3da.jpg', 'Two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy.'),
(516329, '2022-01-06 06:02:05', 'Antlers', '2021-10-28', '/9fzNf2QcsHVvdx5g5QUOgAWpADw.jpg', 'A small-town Oregon teacher and her brother, the local sheriff, discover a young student is harbouring a dangerous secret that could have frightening consequences.'),
(517088, '2022-01-06 06:02:05', 'Being the Ricardos', '2021-12-10', '/4wfA61Mi6E8GncUn8ze4w0jz0Za.jpg', 'Follows Lucille Ball and Desi Arnaz as they face a crisis that could end their careers and another that could end their marriage.'),
(522016, '2022-01-06 06:02:04', 'The 355', '2022-01-05', '/oSNqhngemquRBzxKSC3ysAmnC5e.jpg', 'A group of top female agents from government agencies around the globe try to stop an organization from acquiring a deadly weapon to send the world into chaos.'),
(542178, '2022-01-06 06:02:05', 'The French Dispatch', '2021-10-21', '/u4Vm8n0suBYimsUoarqMw5vxNU8.jpg', 'The quirky staff of an American magazine based in 1970s France puts out its last issue, with stories featuring an artist sentenced to life imprisonment, student riots, and a kidnapping resolved by a chef.'),
(546121, '2022-01-06 06:02:04', 'Run', '2020-11-20', '/rLchzndbDRy41J9X363pMePbV5x.jpg', 'Chloe, a teenager who is confined to a wheelchair, is homeschooled by her mother, Diane. Chloe soon becomes suspicious of her mother and begins to suspect that she may be harboring a dark secret.'),
(554230, '2022-01-06 06:02:04', 'The Lost Daughter', '2021-12-16', '/ue7p1gBxBZeM9KNtwcUnBzdlRHk.jpg', 'A woman\'s seaside vacation takes a dark turn when her obsession with a young mother forces her to confront secrets from her past.'),
(557946, '2022-01-06 06:02:05', 'Last Looks', '2021-12-02', '/jiFHFWIafrxJ5FGrvyOS0ISgRws.jpg', 'A disgraced ex-cop seeks solace by moving to the woods, but his quiet life comes to an end when a private eye recruits him to investigate the murder of an eccentric TV star\'s wife.'),
(559907, '2022-01-06 06:02:05', 'The Green Knight', '2021-07-29', '/al0aXl47cWkf4jnKuPiEZtjWT8j.jpg', 'An epic fantasy adventure based on the timeless Arthurian legend, The Green Knight tells the story of Sir Gawain, King Arthur\'s reckless and headstrong nephew, who embarks on a daring quest to confront the eponymous Green Knight, a gigantic emerald-skinned stranger and tester of men.'),
(567690, '2022-01-06 06:02:04', 'Dear Evan Hansen', '2021-09-24', '/anl65DJYFyp2m0lXaFvlCrSOT8E.jpg', 'Evan Hansen, a high schooler with social anxiety, unintentionally gets caught up in a lie after the family of a classmate who committed suicide mistakes one of Hansen’s letters for their son’s suicide note.'),
(568124, '2022-01-06 06:02:05', 'Encanto', '2021-11-24', '/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg', 'The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family\'s last hope.'),
(571648, '2022-01-06 06:02:05', 'Beasts Clawing at Straws', '2020-02-19', '/1yqVaDR7uIA3Xx9GQIhbEbh5pEe.jpg', 'The destinies of hard-luck lowlifes slowly converge and come crashing down: Jung-man barely gets by working at a sauna and taking care of his sick mother until he finds a bag full of cash in the locker room; Tae-young is in trouble after his girlfriend runs away with the money he borrowed from a loan shark. Soon, a dead body mysteriously turns up; Mi-ran, caught between her husband’s violence and a dead-end job as a bar hostess, she finds a young lover, Jin-tae who offers to kill her husband… And now their dog-eat-dog game starts.'),
(574060, '2022-01-06 06:02:05', 'Gunpowder Milkshake', '2021-07-14', '/mR4PeGrxdEoAc1i5kN7Q2lOFAA5.jpg', 'In her turbulent life as a professional assassin, Sam has no choice but to go rogue to save the life of an innocent 8-year-old girl in the middle of the gang war she has unleashed.'),
(575322, '2022-01-06 06:02:05', 'Project Gemini', '2022-01-06', NULL, 'A sci-fi thriller about a space mission sent to terraform a distant planet. However, the mission encounters something unknown that has its own plan for the planet.'),
(575813, '2022-01-06 06:02:05', 'Better Days', '2019-10-25', '/pi3yXaJzVxZUayUfqMekcsN199A.jpg', 'A bullied teenage girl forms an unlikely friendship with a mysterious young man who protects her from her assailants, while she copes with the pressures of her final examinations.'),
(576845, '2022-01-06 06:02:05', 'Last Night in Soho', '2021-10-21', '/eTUFS0aj81tdtz464wgGXDt7lm2.jpg', 'A young girl, passionate about fashion design, is mysteriously able to enter the 1960s where she encounters her idol, a dazzling wannabe singer. But 1960s London is not what it seems, and time seems to be falling apart with shady consequences.'),
(580489, '2022-01-06 06:02:05', 'Venom: Let There Be Carnage', '2021-09-30', '/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg', 'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.'),
(585245, '2022-01-06 06:02:05', 'Clifford the Big Red Dog', '2021-11-10', '/1Wlwnhn5sXUIwlxpJgWszT622PS.jpg', 'As Emily struggles to fit in at home and at school, she discovers a small red puppy who is destined to become her best friend. When Clifford magically undergoes one heck of a growth spurt, becomes a gigantic dog and attracts the attention of a genetics company, Emily and her Uncle Casey have to fight the forces of greed as they go on the run across New York City. Along the way, Clifford affects the lives of everyone around him and teaches Emily and her uncle the true meaning of acceptance and unconditional love.'),
(586707, '2022-01-06 06:02:05', 'Life Like', '2019-05-14', '/v63dgsTmcgcnh3c10c6Cxy2Y9Ta.jpg', 'An idealistic attractive young couple acquires a stunning, life-like robot for guilt free help, but as the three grow closer, their perception of humanity will be altered forever.'),
(588921, '2022-01-06 06:02:05', 'Ainbo: Spirit of the Amazon', '2021-02-09', '/3GgkzCDq6KYpcmJmcOKh27hYRyj.jpg', 'An epic journey of a young hero and her Spirit Guides, \'Dillo\' a cute and humorous armadillo and \"Vaca\" a goofy oversized tapir, who embark on a quest to save their home in the spectacular Amazon Rainforest.'),
(589752, '2022-01-06 06:02:05', 'Champion of the World', '2021-12-30', '/tinzdtP3olS0ZUznIrC25K3UTmP.jpg', 'Some sporting victories are about more than just claiming a title. Some of them go down in history. The film follows the most dramatic and legendary showdown in the history of chess – the match between Anatoly Karpov, then world champion, and Viktor Korchnoi, a recent emigrant from the USSR. In this battle between two outstanding chess players, a duel of personalities under immense psychological pressure, the stakes are incomprehensibly high.'),
(591538, '2022-01-06 06:02:05', 'The Tragedy of Macbeth', '2021-12-05', '/x1d11fjOMGcAsi0ehxJ7l7u7HS2.jpg', 'Macbeth, the Thane of Glamis, receives a prophecy from a trio of witches that one day he will become King of Scotland. Consumed by ambition and spurred to action by his wife, Macbeth murders his king and takes the throne for himself.'),
(592695, '2022-01-06 06:02:05', 'Pleasure', '2021-10-08', '/y0LhmaMYpFkIfrUlOpJYTVMH2eA.jpg', '20-year-old Bella Cherry leaves her small town in Sweden for Los Angeles with the aim to become the world\'s next big porn star but the road to her goal turns out to be bumpier than she imagined.'),
(592863, '2022-01-06 06:02:05', 'Respect', '2021-08-12', '/m0ppE0yXQeFWzlwLdDUFRfanp9R.jpg', 'The rise of Aretha Franklin’s career from a child singing in her father’s church’s choir to her international superstardom.'),
(597208, '2022-01-06 06:02:05', 'Nightmare Alley', '2021-12-02', '/g0YNGpmlXsgHfhGnJz3c5uyzZ1B.jpg', 'An ambitious young carny with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist who is even more dangerous than he is.'),
(597859, '2022-01-06 06:02:05', 'The Pilot: A Battle for Survival', '2021-12-02', '/rT5qZsUSUHP008yeqZQFD1EHbkt.jpg', 'December of 1941, Northwestern Front. A German tank column is moving towards Moscow. During a mission to stop the enemy advance, Nikolai Komlev\'s IL-2 is shot down. Komlev manages to crash-land his plane in a remote forest clearing. He\'s alive, but far from friendly territory. Ahead of him is a relentless trial of severe physical and mental endurance. After battling hunger and extreme cold, evading packs of wolves and detachments of Nazi soldiers, the wounded Komlev finally makes it back to safety. But there he faces another challenge, the most life-changing of them all.'),
(597890, '2022-01-06 06:02:05', 'Voyagers', '2021-04-08', '/9dBSwftCzkC4K4zgMZTwcm58VUR.jpg', 'With the future of the human race at stake, a group of young men and women -- bred for intelligence and obedience -- embark on an expedition to colonize a distant planet. When they uncover disturbing secrets about the mission, they defy their training and begin to explore their most primitive natures. As life on the ship descends into chaos, they soon become consumed by fear, lust and an insatiable hunger for power.'),
(598014, '2022-01-06 06:02:05', 'The Last Warrior: A Messenger of Darkness', '2021-12-23', '/yfZgMbRieUEJr4ROvj5cqATly25.jpg', 'Now that Ivan is about to turn 21, he is now grown up and finally old enough to marry the beautiful Vasilisa. But when Vasilisa is kidnapped and trapped in modern Moscow, Ivan and his friends must travel to the present day to rescue her.'),
(600583, '2022-01-06 06:02:05', 'The Power of the Dog', '2021-09-13', '/gAsHuCQMN7mv4uFIvM4ACQ09hPr.jpg', 'A domineering but charismatic rancher wages a war  of intimidation on his brother\'s new wife and her teen son, until long-hidden secrets come to light.'),
(601337, '2022-01-06 06:02:05', '\'83', '2021-12-24', '/ziBtDlzSGxBqv8hvOzNQCeJVJRW.jpg', 'On the 25th of June 1983, the Lord’s Cricket Ground witnessed one of the biggest underdog stories in the history of sports. Fourteen inspired players - led by a man\'s self-belief and conviction - fought against all odds and orchestrated India’s greatest sporting triumph by beating the two-time World Champions West Indies.'),
(602211, '2022-01-06 06:02:05', 'Fatman', '2020-10-19', '/ckfwfLkl0CkafTasoRw5FILhZAS.jpg', 'A rowdy, unorthodox Santa Claus is fighting to save his declining business. Meanwhile, Billy, a neglected and precocious 12 year old, hires a hit man to kill Santa after receiving a lump of coal in his stocking.'),
(603661, '2022-01-06 06:02:05', 'The Hating Game', '2021-12-09', '/wbJ5tvyXK3ZK1kVdzenFYXFvfpH.jpg', 'Resolving to achieve professional success without compromising her ethics, Lucy embarks on a ruthless game of one-upmanship against cold and efficient nemesis Joshua, a rivalry that is complicated by her growing attraction to him.'),
(604563, '2022-01-06 06:02:05', 'OSS 117: From Africa with Love', '2021-08-04', '/oKL8y3MoXtsEMVo2MlPiUaAHWJz.jpg', 'The third entry in secret agent OSS 117\'s parodic spy adventures.'),
(607430, '2022-01-06 06:02:05', 'Nine Days', '2021-07-15', '/xYwxwJ6fD4myHhMXi1jSRhKVhW3.jpg', 'A reclusive man conducts a series of interviews with human souls for a chance to be born.'),
(610321, '2022-01-06 06:02:04', 'The Policeman\'s Lineage', '2022-01-05', '/hnZGMvRaO1vxzq9wQz5nGrbPkJv.jpg', 'Min-jae who is a policeman from generation to generation has been ordered to investigate Kang-yoon secretly, who is the ace team leader of investigation team. Min-jae is appointed as the member of Kang-yoon’s team. Min-jae has belief of “If the police do something illegal even it has been occurred during the process of investigation, he is also a criminal.” But while Min-jae investigates Kang-yoon, he begins to resemble Kang-yoon who has belief of “The chase of crime should be justified even it’s illegal.” Will Min-jae be able to clear his private mission and arrest Kang-yoon that he trusts and admires?'),
(611914, '2022-01-06 06:02:05', 'The Courier', '2019-11-22', '/ne4QPHn56Z1vxk6iKJKvDnmNI9Y.jpg', 'This intense action-thriller unfolds in real time as two embattled souls fight for their lives. Gary Oldman stars as a vicious crime boss out to kill Nick, the lone witness set to testify against him. He hires a mysterious female motorcycle courier to unknowingly deliver a poison-gas bomb to slay Nick, but after she rescues Nick from certain death, the duo must confront an army of ruthless hired killers in order to survive the night.'),
(613335, '2022-01-06 06:02:05', 'Les Tuche 4', '2021-12-08', '/j0AEXlvTMjLdaVO27VA4vsioawe.jpg', 'After having resigned from his post as President of the Republic, Jeff and his family are happy to be back in their village of Bouzolles. As the end of the year holidays approach, Cathy asks for a unique gift: to reconnect with her sister Maguy, and her husband Jean-Yves, with whom Jeff has been angry for 10 years. The reconciliation could have gone smoothly, except that during a lunch, Jeff and Jean-Yves, will once again find a subject of contention: CHRISTMAS. This family feud, which should never have left Bouzolles, will turn into a standoff between Jeff and a giant of Internet distribution.'),
(614917, '2022-01-06 06:02:05', 'King Richard', '2021-11-18', '/4kb7uR1UmXa33U6GB6F9xckFlhn.jpg', 'The story of how Richard Williams served as a coach to his daughters Venus and Serena, who will soon become two of the most legendary tennis players in history.'),
(615666, '2022-01-06 06:02:05', 'A Boy Called Christmas', '2021-11-25', '/odKqOY6VE6C59YAdGHB0b5Havye.jpg', 'An ordinary young boy called Nikolas sets out on an extraordinary adventure into the snowy north in search of his father who is on a quest to discover the fabled village of the elves, Elfhelm. Taking with him a headstrong reindeer called Blitzen and a loyal pet mouse, Nikolas soon meets his destiny in this magical and endearing story that proves nothing is impossible…'),
(617502, '2022-01-06 06:02:05', 'Jolt', '2021-07-15', '/wPjtacig0kIkVcTQmXoNt6jbMwo.jpg', 'A bouncer with an anger management problem goes on a furious and resentful rampage after the murder of a friend.'),
(617762, '2022-01-06 06:02:05', 'The Electrical Life of Louis Wain', '2021-10-21', '/znpokr30qWVJztgO3t98PVyFLdC.jpg', 'The extraordinary true story of eccentric British artist Louis Wain, whose playful, sometimes even psychedelic pictures helped to transform the public\'s perception of cats forever.'),
(618416, '2022-01-06 06:02:04', 'Penguin Bloom', '2021-01-21', '/2dWWf6qjVU0TklCUKCUra1Yqfz3.jpg', 'When an unlikely ally enters the Bloom family\'s world in the form of an injured baby magpie they name Penguin, the bird’s arrival makes a profound difference in the struggling family’s life.'),
(619594, '2022-01-06 06:02:05', 'My Salinger Year', '2021-01-14', '/qyCFlYcxdgU4Dodfw4QWtK59Trk.jpg', 'A college grad takes a clerical job working for the literary agent of the renowned, reclusive writer J.D. Salinger.'),
(619803, '2022-01-06 06:02:05', 'The Outlaws 2', '2022-01-01', NULL, 'The sequel to the 2017 crime action movie \"The Outlaws\".'),
(624860, '2022-01-06 06:02:05', 'The Matrix Resurrections', '2021-12-16', '/hv7o3VgfsairBoQFAawgaQ4cR1m.jpg', 'Plagued by strange memories, Neo\'s life takes an unexpected turn when he finds himself back inside the Matrix.'),
(627639, '2022-01-06 06:02:05', 'Ana\'s Desire', '2021-12-30', '/yprA2X3x6CPdIAgHxktkSSRXZDs.jpg', 'Ana and her son Mateo live in a middle class apartment in Mexico City. The family routine takes a turn when Juan arrives to visit them after several years of absence. The reunion unleashes memories and secrets of their past that Ana will have to confront in order to find, at last, the peace of mind that has been lacking for so long.'),
(630240, '2022-01-06 06:02:04', 'Titane', '2021-07-14', '/zEddiBK6yZNUGVnmBJzmnYcEWiR.jpg', 'A woman with a metal plate in her head from a childhood car accident embarks on a bizarre journey, bringing her into contact with a firefighter who\'s reunited with his missing son after 10 years.'),
(631947, '2022-01-06 06:02:05', 'The Legend of La Llorona', '2020-01-01', '/9BQPM1Fa1hdXaE7hNafO5WWNv9v.jpg', 'While vacationing in Mexico, a couple discovers their son\'s disappearance is tied to a supernatural curse.'),
(632617, '2022-01-06 06:02:05', 'C\'mon C\'mon', '2021-11-19', '/lXGa1MgoqfgmcDSvKSPsueT9n73.jpg', 'Johnny and his young nephew forge a tenuous but transformational relationship when they embark on a cross-country trip to see life away from Los Angeles.'),
(634649, '2022-01-06 06:02:05', 'Spider-Man: No Way Home', '2021-12-15', '/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.'),
(635731, '2022-01-06 06:02:05', 'Pig', '2021-07-16', '/ngT5lZ37bvryz5popo1IDOh03WL.jpg', 'A truffle hunter who lives alone in the Oregon wilderness must visit Portland to find the mysterious person who stole his beloved foraging pig.'),
(639721, '2022-01-06 06:02:05', 'The Addams Family 2', '2021-10-01', '/wfrfxivLOBtGMC98tIr2LSOeKSe.jpg', 'The Addams get tangled up in more wacky adventures and find themselves involved in hilarious run-ins with all sorts of unsuspecting characters.'),
(643532, '2022-01-06 06:02:05', 'The Card Counter', '2021-09-03', '/r7dJqfmspzVlHYWXBiKn7NP8ZBw.jpg', 'William Tell just wants to play cards. His spartan existence on the casino trail is shattered when he is approached by Cirk, a vulnerable and angry young man seeking help to execute his plan for revenge on a military colonel. Tell sees a chance at redemption through his relationship with Cirk. But keeping Cirk on the straight-and-narrow proves impossible, dragging Tell back into the darkness of his past.'),
(644089, '2022-01-06 06:02:04', 'Blue Bayou', '2021-09-10', '/wETWXzbvn0LhrPGLeRqyIeIl0E8.jpg', 'As a Korean-American man raised in the Louisiana bayou works hard to make a life for his family, he must confront the ghosts of his past as he discovers that he could be deported from the only country he has ever called home.'),
(644495, '2022-01-06 06:02:05', 'House of Gucci', '2021-11-24', '/jdLsmpqmP1wTdFUPtmxMnYgoifT.jpg', 'When Patrizia Reggiani, an outsider from humble beginnings, marries into the Gucci family, her unbridled ambition begins to unravel the family legacy and triggers a reckless spiral of betrayal, decadence, revenge, and ultimately…murder.'),
(644583, '2022-01-06 06:02:04', 'The Mauritanian', '2021-02-10', '/sfCptvwspPrO4RZ3y06GYyTEfE3.jpg', 'A detainee at the U.S military\'s Guantanamo Bay detention center is held without charges for over a decade and seeks help from a defense attorney for his release.'),
(645788, '2022-01-06 06:02:05', 'The Protégé', '2021-08-19', '/fbTxsnJcQwuwzCEu9VEiU9lV75Y.jpg', 'Rescued as a child by the legendary assassin Moody and trained in the family business, Anna is the world’s most skilled contract killer. When Moody, the man who was like a father to her and taught her everything she needs to know about trust and survival, is brutally killed, Anna vows revenge. As she becomes entangled with an enigmatic killer whose attraction to her goes way beyond cat and mouse, their confrontation turns deadly and the loose ends of a life spent killing will weave themselves ever tighter.'),
(645886, '2022-01-06 06:02:05', 'The Unforgivable', '2021-11-24', '/kbOB9DGl8qwhDRcXOmXfmcmadeD.jpg', 'A woman is released from prison after serving a sentence for a violent crime and re-enters a society that refuses to forgive her past.'),
(646207, '2022-01-06 06:02:04', 'The Ice Road', '2021-06-24', '/5MlvT4DZIdkpb7A9t375HVoiJ1v.jpg', 'After a remote diamond mine collapses in far northern Canada, an ice road driver must lead an impossible rescue mission over a frozen ocean to save the trapped miners.'),
(646380, '2022-01-06 06:02:05', 'Don\'t Look Up', '2021-12-07', '/nvxrQQspxmSblCYDtvDAbVFX8Jt.jpg', 'Two low-level astronomers must go on a giant media tour to warn humankind of an approaching comet that will destroy planet Earth.'),
(651915, '2022-01-06 06:02:05', 'Intervenção', '2021-12-26', '/gR2OfaUYgLF8s9lU15dYx9n1swf.jpg', 'Larissa competed for the Rio Military Police in search of the ideal of “protecting the citizen”.'),
(652837, '2022-01-06 06:02:05', 'Josee, the Tiger and the Fish', '2020-12-25', '/dmZfiaSvBoCMTdyUsEqGql4yqul.jpg', 'With dreams of diving abroad, Tsuneo gets a job assisting Josee, an artist whose imagination takes her far beyond her wheelchair. But when the tide turns against them, they push each other to places they never thought possible, and inspire a love fit for a storybook.'),
(654897, '2022-01-06 06:02:05', 'Estado Impuro', '2022-01-05', NULL, 'Drama about marriage.'),
(656991, '2022-01-06 06:02:05', 'Wild Indian', '2021-09-03', '/kGyl8SCp9We2eTjRydqjJQJ18tg.jpg', 'Decades after covering up his classmate’s murder, Michael has moved on from his reservation and fractured past. When a man who shares his violent secret seeks vengeance, Michael goes to great lengths to protect his new life with his wife and boss from the demons of his past.'),
(660120, '2022-01-06 06:02:04', 'The Worst Person in the World', '2021-10-13', '/3DgGjoMjd188LN4v24Kw7iClKbT.jpg', 'Chronicles four years in the life of Julie, a young woman who navigates the troubled waters of her love life and struggles to find her career path, leading her to take a realistic look at who she really is.'),
(661791, '2022-01-06 06:02:05', 'The Grandmother', '2022-01-05', NULL, 'A Paris model must return to Madrid where her grandmother, who raised her, has had a stroke. But spending just a few days with this relative turns into an unexpected nightmare.'),
(663260, '2022-01-06 06:02:05', 'Black Box', '2021-09-08', '/1KIWr83GPeO1Z54lndzs2H4OoBe.jpg', 'Matthieu is a young and talented black box analyst on a mission to solve the reason behind the deadly crash of a brand new aircraft. Yet, when the case is closed by authorities, Matthieu cannot help but sense there is something wrong with the evidence. As he listens to the tracks again, he starts detecting some seriously disturbing details. Could the tape have been modified? Going against his boss\' orders, Matthieu begins his own rogue investigation - an obsessional and dangerous quest for truth that will quickly threatan far more than his career...'),
(664574, '2022-01-06 06:02:04', 'Silent Night', '2021-12-03', '/nJYAAOk74VjPlwz34jWFh8MPw2r.jpg', 'Nell, Simon, and their boy Art are ready to welcome friends and family for what promises to be a perfect Christmas gathering. Perfect except for one thing: everyone is going to die.'),
(665474, '2022-01-06 06:02:05', 'After the Crossing', '2022-01-05', '/wYIJtWGNlfErgE0VvMrp2LYFvux.jpg', 'Having made it to Italy, an Ivorian named Inza now plans to cross the mountains to France. Without stylisation, the film observes his everyday life: affairs with women, brushes with European asylum law and the impossibility of finding peace.'),
(669659, '2022-01-06 06:02:05', 'Best Sellers', '2021-09-17', '/oqtAlHqntNqjzDXbwu2KCkSkKxz.jpg', 'A cranky, retired author reluctantly embarks on a final book tour to help out a young publisher.'),
(670940, '2022-01-06 06:02:05', 'El Chapo and the Curse of the Pirate Zombies', '2021-12-31', NULL, 'A sexy soap opera actress, a Hollywood movie star /wannabe journalist and a Mexican drug lord fight zombie pirates.'),
(671043, '2022-01-06 06:02:05', 'Spoiled Brats', '2021-09-15', '/b6UXXuRQL3teEMVKTyae5hTq8ke.jpg', 'The billionaire is tired of the whims of his own children and decides to teach them a lesson. He announces to them that he has become bankrupt. Now spoiled teenagers will have to do what they have never done: go to work, learn to love and value life.'),
(671269, '2022-01-06 06:02:05', 'El Diario de Karem', '2021-12-31', NULL, 'A possessed young girl from an atheist family refuses to let her new powers go and becomes more than a threat to everyone besides her.'),
(673121, '2022-01-06 06:02:05', 'Wolf', '2021-12-03', '/gU4MTmcZeNoFy0jlKwADO3NKAe0.jpg', 'Jacob, a man who believes he is a wolf trapped in a human body, is sent to a clinic by his family where he is forced to undergo increasingly extreme forms of \"curative\" therapies at the hands of The Zookeeper. Jacob’s only solace is the enigmatic wildcat with whom he roams the hospital in the dead of night. The two form an improbable friendship that develops into infatuation.'),
(673309, '2022-01-06 06:02:05', 'American Underdog', '2021-12-25', '/cffLySrYq1KlIFpGKWjGANoGaxs.jpg', 'The true story of Kurt Warner, who went from a stockboy at a grocery store to a two-time NFL MVP, Super Bowl champion, and Hall of Fame quarterback.'),
(674164, '2022-01-06 06:02:05', 'Return of Chucky', '2021-12-31', NULL, 'The fan movie follows the story of Andrew, a kid who finds a terrifying deteriorated Good Guy doll at the forest. Soon, a chain of blood is unleashed after several murders, which leaves the trail that the doll, named Chucky, is possessed, and will kill anyone who crosses in his way to complete his terrifying and dirty plan.'),
(675024, '2022-01-06 06:02:05', 'The Exorcism of Carmen Farias', '2021-05-05', '/zm2kMjiz0u6qdn2XKbEbQkDiltN.jpg', 'Carmen, a brave journalist, discovers soon after her mother\'s death that she has inherited her grandma\'s house. She decides to move there without knowing it hides dark secrets.'),
(678512, '2022-01-06 06:02:05', 'Sound of Freedom', '2022-01-01', NULL, 'The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.'),
(680058, '2022-01-06 06:02:05', 'The Rescue', '2021-10-08', '/gOBKWe6lHlt8srk11TFlDuBtl0H.jpg', 'The enthralling, against-all-odds story that transfixed the world in 2018: the daring rescue of twelve boys and their coach from deep inside a flooded cave in Northern Thailand.'),
(683311, '2022-01-06 06:02:05', 'Castle Falls', '2021-12-03', '/ver27ON3Yo5GfvR1VNHO9tTtOdT.jpg', 'Rival gangs seek out millions of dollars hidden inside a luxury condominium that\'s scheduled to be demolished, but first they have to deal with the demolition prep crewman who found the loot first.'),
(684281, '2022-01-06 06:02:05', 'Adventures of a Mathematician', '2021-06-11', '/npEUveGYH2H7VTlM8k6xH6Jcvqr.jpg', 'The warmhearted story of Polish immigrant and mathematician Stan Ulam, who moved to the U.S. in the 1930s. Stan deals with the difficult losses of family and friends all while helping to create the hydrogen bomb and the first computer.'),
(712128, '2022-01-06 06:02:05', 'Broken Keys', '2022-01-06', NULL, 'A pianist tries to escape his persecuted Middle-eastern town where modern ways of living and music have been banned by an extremist group.'),
(712454, '2022-01-06 06:02:05', 'The Summit of the Gods', '2021-09-22', '/b5KG17zlqMupml1AET1Ba3xgro0.jpg', 'A photojournalist’s obsessive quest for the truth about the first expedition to Mt. Everest leads him to search for an esteemed climber who went missing.'),
(714968, '2022-01-06 06:02:05', 'Plan A', '2021-08-16', '/c2cb0lLvbzvHlSUo35W8CfP0kYO.jpg', 'Germany 1945, Max, a Jewish Holocaust survivor, meets a radical group of Jewish resistance fighters, who, like him, lost all hope for their future after they were robbed of their existence and their entire families were killed by the Nazis. They dream of retaliation on an epic scale for the Jewish people. An eye for an eye, a tooth for a tooth. Max starts identifying with the group\'s monstrous plans...'),
(716612, '2022-01-06 06:02:04', 'Spencer', '2021-11-04', '/2nJJxHjBTDVDIbpHylCsDVQ3alG.jpg', 'During her Christmas holidays with the royal family at the Sandringham estate in Norfolk, England, Diana decides to leave her marriage to Prince Charles.'),
(718032, '2022-01-06 06:02:05', 'Licorice Pizza', '2021-11-26', '/9tPV2VnrikL8LPcKnnGODU9P9Ma.jpg', 'The story of Alana Kane and Gary Valentine growing up, running around and going through the treacherous navigation of first love in the San Fernando Valley, 1973.'),
(718509, '2022-01-06 06:02:05', 'Cinta Pertama, Kedua & Ketiga', '2022-01-06', '/qYEUpgBmdDWdQExX45pbKR2dMF5.jpg', 'Raja & Asia have the same responsibility, taking care of their two single parents respectively. If Raja wants to live independently like his two sisters, Asia has chosen to be devoted to her mother who she feels has sacrificed everything for her. Then, Dewa & Linda, their parents, began to unite their hearts. Raja was happy, Asia hesitated. When Raja convinces Asia that their parents are compatible together, Raja & Asia slowly fall in love.'),
(722778, '2022-01-06 06:02:05', 'The Hand of God', '2021-11-24', '/dTvGUMFc5WCziTzXZKZ2EfW2bEM.jpg', 'In 1980s Naples, young Fabietto pursues his love for football as family tragedy strikes, shaping his uncertain but promising future as a filmmaker.'),
(728526, '2022-01-06 06:02:05', 'Encounter', '2021-12-03', '/zlj0zHo67xXoj7hvwGtaKRkSdBV.jpg', 'A decorated Marine goes on a rescue mission to save his two young sons from an unhuman threat. As their journey takes them in increasingly dangerous directions, the boys will need to leave their childhoods behind.'),
(729577, '2022-01-06 06:02:05', 'The Last Son', '2021-12-10', '/6p4yHucexKDgsZmHw6TQXkMIEiO.jpg', 'Sam Worthington stars as Isaac LeMay, a murderous outlaw who learns he is cursed by a prophecy: one of his children will kill him. To prevent this, he hunts down each of his estranged children including long-lost son Cal (Colson Baker). With bounty hunters and Sheriff Solomon (Thomas Jane) on his tail, LeMay must find a way to stop his children and end the curse.'),
(729679, '2022-01-06 06:02:04', 'Toma', '2021-12-20', '/q0Jv1Hd8V80aH46eQ9dDgabSFCw.jpg', 'Biopic about Serbian folk singer Toma Zdravković, the man who is remembered not only for his songs and unique way he was singing them, but also as a bohemian, both in his behavior and his soul.'),
(730167, '2022-01-06 06:02:05', 'The Reef: Stalked', '2022-01-06', '/fsVWZQzG8ayJyCR4i0Uw8mVLqzo.jpg', 'In an effort to heal after witnessing her sister’s horrific murder, Nic travels to a tropical resort with her friends for a kayaking and diving adventure. Only hours into their expedition, the women are stalked and then attacked by a great white shark. To survive they will need to band together and Nic will have to overcome her post-traumatic stress, face her fears and slay the monster.'),
(737676, '2022-01-06 06:02:05', 'The ExorSIS', '2021-12-25', '/6JB4hJdCrBMnd84U7ODnnEyjpOi.jpg', 'The film follows Gina, who must find an exorcist after her younger sister gets possessed by a dead woman’s spirit.'),
(738362, '2022-01-06 06:02:05', 'The Fresh Prince of Bel-Air Reunion Special', '2020-11-18', '/hzbrQ8gR26R6BWbrp3HaPCRs08T.jpg', 'Join Will Smith, Tatyana Ali, Karyn Parsons, Joseph Marcell, Daphne Maxwell Reid, Alfonso Ribeiro and DJ Jazzy Jeff, for a funny and heartfelt night full of music and dancing in honor of the show that ran for six seasons and 148 episodes.'),
(743439, '2022-01-06 06:02:05', 'PAW Patrol: Jet To The Rescue', '2020-09-10', '/vwpxy4kmQyW5aBJ3uxhQM6koU6H.jpg', 'A royal relative steals a gem with the power to make things fly, the Paw Patrol takes to the skies to stop him and save Barkingburg.'),
(749274, '2022-01-06 06:02:05', 'Cry Macho', '2021-09-16', '/g6wufgtycJCP508tlC3crSYFCgC.jpg', 'Mike Milo, a one-time rodeo star and washed-up horse breeder, takes a job from an ex-boss to bring the man\'s young son home from Mexico.'),
(753232, '2022-01-06 06:02:05', 'The Commando', '2022-01-07', '/pnZ9NMxRqbcJ2dPNROIoregruv5.jpg', 'An elite DEA agent returns home after a failed mission when his family makes an unexpected discovery in their house – a stash of money worth $3 million. They soon face the danger and threat of a newly released criminal and his crew, who will do whatever it takes to retrieve the money, including kidnap the agent’s daughters. Stakes are high and lives are at risk in this head-to-head battle as the agent stops at nothing to protect his family against the money-hungry criminals.'),
(753926, '2022-01-06 06:02:05', 'Toys of Terror', '2021-12-02', '/j6Er72CMHKiZgFr0HBMbuyj7Ssa.jpg', 'A big family moves into a dusty old house in the snowy woods of Washington with hopes of it being a nice holiday escape. But the kids soon discover a stash of old toys that just so happen to belong to a creepy ghost boy. As stranger and stranger things start to happen, some of the kids begin to sense that something in the house is not quite right…'),
(754067, '2022-01-06 06:02:05', 'Vicky and Her Mystery', '2021-12-15', '/vo9MRyCMBAdSqZgkI70AfVg8ISI.jpg', 'Stéphane decides to move to the beautiful mountains of Cantal in order to reconnect with his 8-year-old daughter, Victoria, who has been silent since her mother\'s disappearance. During a walk in the forest, a shepherd gives Victoria a puppy named \"Mystery\" who will gradually give her a taste for life. But very quickly, Stéphane discovers that the animal is in reality a wolf… Despite the warnings and the danger of this situation, he cannot bring himself to separate his daughter from this seemingly harmless ball of hair.'),
(754934, '2022-01-06 06:02:05', 'Son', '2021-08-06', '/mRZDHjArYNWpOv06kxRK1cduQKh.jpg', 'When a young boy contracts a mysterious illness, his mother must decide how far she will go to protect him from terrifying forces in her past.'),
(755437, '2022-01-06 06:02:05', 'Mamá o papá', '2021-12-17', '/4VL5C8s3y2efpB03SvCD3eFxg1i.jpg', 'Flora and Victor are fun, modern, caring parents. That is, until they decide to get a divorce, and the perfect job opportunity turns up for them. They now have one problem: custody.'),
(758866, '2022-01-06 06:02:05', 'Drive My Car', '2021-08-18', '/esOyr2JE2mpvNpNZLqszRSnrnap.jpg', 'Yusuke Kafuku, a stage actor and director, still unable, after two years, to cope with the loss of his beloved wife, accepts to direct Uncle Vanja at a theater festival in Hiroshima. There he meets Misaki, an introverted young woman, appointed to drive his car. In between rides, secrets from the past and heartfelt confessions will be unveiled.'),
(760873, '2022-01-06 06:02:05', 'The Colony', '2021-08-26', '/vZUpGL9SgS3q5lmEoaXKbxwgh9G.jpg', 'In the not-too-distant future: after a global catastrophe has wiped out nearly all of humanity on Earth, an elite astronaut from Space Colony Kepler must make a decision that will seal the fate of the people on both planets.'),
(761898, '2022-01-06 06:02:05', 'Sword Art Online the Movie -Progressive- Aria of a Starless Night', '2021-10-30', '/qKVOTKPPtvoXd75L1HOSBPLtKWS.jpg', 'One month after Kayaba Akihiko\'s game of death began, the death toll continues to rise, two thousand players having already lost their lives to the ultra-difficult VRMMO world of Sword Art Online. On the day of the strategy meeting to plan out the first-floor boss battle, Kirito, a solo player who vows to fight alone to get stronger, runs into a rare, high-level female player. She gracefully dispatches powerful monsters with a single rapier that flashes like a shooting star in the night...'),
(762006, '2022-01-06 06:02:04', 'The Lost Girls', '2021-12-25', '/hVom0Vdf7PqtAf0HSXgwlx6Fq1L.jpg', 'Like her grandmother and her mother Jane before her, Wendy must escape Pan\'s hold on her and the promise he wants her to keep. As her daughter Berry comes into Pan\'s orbit, Wendy must fight to save her relationship with her daughter while reconciling her legacy.'),
(762433, '2022-01-06 06:02:05', 'Zeros and Ones', '2021-11-18', '/uWGPC7j70LE64nbetxQGSSYJO53.jpg', 'Called to Rome to stop an imminent terrorist bombing, a soldier desperately seeks news of his imprisoned brother — a rebel with knowledge that could thwart the attack. Navigating the capital\'s darkened streets, he races to a series of ominous encounters to keep the Vatican from being blown to bits.'),
(763164, '2022-01-06 06:02:05', 'Apex', '2021-11-12', '/4gKxQIW91hOTELjY5lzjMbLoGxB.jpg', 'Ex-cop Thomas Malone is serving a life sentence for a crime he didn’t commit. He is offered a chance at freedom if he can survive a deadly game of Apex, in which six hunters pay for the pleasure of hunting another human on a remote island. He accepts, and once he arrives, all hell breaks loose.'),
(763329, '2022-01-06 06:02:05', 'Red Rocket', '2021-12-10', '/7j0FNfCsh13boepeZl1yEQhRbWv.jpg', 'Finding himself down and out in Los Angeles, ex porn star Mikey Saber decides to crawl back to his hometown of Texas City, Texas, where his estranged wife and mother-in-law are living. Just as this dysfunctional family seems to be making things work, Mikey meets a young woman named Strawberry working the cash register at a local doughnut shop.'),
(765245, '2022-01-06 06:02:05', 'Swan Song', '2021-12-17', '/ibdmSDwCpDYNdIkGeu7prsMVzYZ.jpg', 'In the near future, Cameron Turner is diagnosed with a terminal illness. Presented with an experimental solution to shield his wife and son from grief, he grapples with altering their fate.'),
(766105, '2022-01-06 06:02:05', 'A Taste of Hunger', '2021-06-24', '/uq8ZqjgFhmWLj4QzJshnNseVRbx.jpg', 'Maggie and Carsten love each other, they have two wonderful children and run their own gourmet restaurant; Malus. They want it all. And they have it all. Almost. They are missing the coveted Michelin Star. It has been their dream, on which they gambled everything to win. One day Carsten receives a letter saying that his wife loves somebody else. But who sent the letter and why? In their continuous passion and pursuit for the ultimate recognition, they forget that the meals of life are best enjoyed together.'),
(766798, '2022-01-06 06:02:05', 'Parallel Mothers', '2021-10-08', '/6UxCO59sdhvp43OCkrYx4EX61J.jpg', 'Two unmarried women who have become pregnant by accident and are about to give birth meet in a hospital room: Janis, middle-aged, unrepentant and happy; Ana, a teenager, remorseful and frightened.'),
(766907, '2022-01-06 06:02:05', 'American Siege', '2022-01-07', '/yo0TibseCrwVHDu8AnZ65a0w1Um.jpg', 'An ex-NYPD officer-turned-sheriff of a small rural Georgia town has to contend with a gang of thieves who have taken a wealthy doctor hostage.'),
(770254, '2022-01-06 06:02:05', 'Back to the Outback', '2021-12-03', '/5B22eed7ErxFiYAG4Ksb4eLwKNF.jpg', 'Tired of being locked in a reptile house where humans gawk at them like they are monsters, a ragtag group of Australia’s deadliest creatures plot an escape from their zoo to the Outback, a place where they’ll fit in without being judged.'),
(774021, '2022-01-06 06:02:05', 'Demonic', '2021-07-29', '/tFBVXnqmsmoSFR3rbltTfdGIMgV.jpg', 'A young woman unleashes terrifying demons when supernatural forces at the root of a decades-old rift between mother and daughter are ruthlessly revealed.'),
(776305, '2022-01-06 06:02:05', 'Belle', '2021-07-16', '/fhp1Kk7OPBeRqyh19H0StpDzHCz.jpg', 'Suzu is a 17-year-old high school student living in a rural town with her father. Wounded by the loss of her mother at a young age, Suzu one day discovers the massive online world \"U\" and dives into this alternate reality as her avatar, Belle. Before long, all of U\'s eyes are fixed on Belle, when, suddenly, a mysterious dragon-like figure appears before her.'),
(777270, '2022-01-06 06:02:05', 'Belfast', '2021-11-11', '/4RSN2vVKk7M9QhpQfomQjW1JDiU.jpg', 'Buddy is a young boy on the cusp of adolescence, whose life is filled with familial love, childhood hijinks, and a blossoming romance. Yet, with his beloved hometown caught up in increasing turmoil, his family faces a momentous choice: hope the conflict will pass or leave everything they know behind for a new life.');
INSERT INTO `movies` (`movieId`, `timestamp`, `title`, `release_date`, `backdrop_path`, `overview`) VALUES
(777326, '2022-01-06 06:02:05', 'Honest Divorce', '2021-12-09', '/qcb4FxjnQNJUb14R1nD9RcwOGKt.jpg', 'Gena tried all his life to be the support of the family. For this, he even abandoned his stormy youth and dreams of becoming a KVN star. And when, 25 years later, his wife called him boring and offered to divorce, Gena decides to make up for lost time - fill his life with adventure and go to the KVN festival in Sochi. And a new acquaintance pushes him to this journey - a beautiful girl of very easy virtue. She is sure that the talented Gena will quickly become a star of humor with her help. If it doesn\'t disappear even faster, along with a decent amount from Genya\'s card.'),
(778508, '2022-01-06 06:02:05', 'Swingers', '2022-01-06', '/2Hw90B3OsTo50Cydt4KGkez5yI6.jpg', 'People who are very different in social origin, material capabilities, occupation and outlook on life are involved in a curious situation. Wealthy businessman Igor and his girlfriend Olga - a socialite who dreams of a career as a designer; tired from work as a physiotherapist Andrey and his wife, a pharmacist, Irina. The thrill seeking in one case and the desire to find a way out of the family dead end in the other lead these couples to a New Year\'s Eve swinger party. A sexual experiment in both couples, initiated by only one of the partners, turns into a series of incidents and ends in failure. To the surprise of themselves and their \"legitimate\" halves, the heroes reveal real feelings and strong mutual affection.'),
(778819, '2022-01-06 06:02:05', 'Checkered Ninja 2', '2021-08-19', '/7i6F8CiBDHrZ1THxlsjF9EiSkXd.jpg', 'In “CHECKERED NINJA 2”, we again follow the boy Alex and Checkered Ninja on a frantic hunt for the villain from the first movie Phillip Eppermint. Because Eppermint manages to evade a prison sentence in Thailand, CHECKERED Ninja comes alive and seeks out Alex. Together, and with Alex’s entire family, they now have to go to Thailand to bust Eppermint. Alex and Checkered Ninja are swooped up into a dangerous mission, where their friendship sometimes comes under intense pressure.'),
(780382, '2022-01-06 06:02:05', 'The Wolf and the Lion', '2021-10-13', '/vYAuEi9NO23JeutE1REn6RkZUTj.jpg', 'After her grandfather\'s death, 20-year-old Alma decides to go back to her childhood home - a little island in the heart of the majestic Canadian forest. Whilst there, she rescues two helpless cubs: a wolf and a lion. They forge an inseparable bond, but their world soon collapses as the forest ranger discovers the animals and takes them away. The two cub brothers must now embark on a treacherous journey across Canada to be reunited with one another and Alma once more.'),
(785545, '2022-01-06 06:02:05', 'Shaun the Sheep: The Flight Before Christmas', '2021-12-03', '/4JEx2BXhOzuN9pCQcnPSWwCiF0W.jpg', 'Shaun\'s seasonal excitement turns to dismay when a farmhouse raid to get bigger stockings for the flock inadvertently leads to Timmy going missing. Can Shaun get Timmy back before he becomes someone else’s present?'),
(788929, '2022-01-06 06:02:05', 'Lamb', '2021-08-12', '/guPEWOSXsdmwjttcO12h2tLRhFj.jpg', 'An Icelandic couple live with their herd of sheep on a beautiful but remote farm. When they discover a mysterious newborn on their land, they decide to keep it and raise it as their own. This unexpected development and the prospects of a new family brings them much joy before ultimately destroying them.'),
(788935, '2022-01-06 06:02:04', 'Mali Twist', '2022-01-05', '/e7EWZjoQDUjVcxaD0xYcfaCC9FM.jpg', 'Mali, 1960. The youth of Bamako dance the twist to rock and roll music newly imported from the West and dream of political renewal. Samba, a young socialist, falls for spirited Lara during one of his missions to the bush. To escape her forced marriage, she secretly flees with him to the city. But Lara’s husband won’t let them be and the Revolution soon brings painful disillusions as they dream of a future together.'),
(790226, '2022-01-06 06:02:05', 'Yo, traidor', '2022-01-06', NULL, ''),
(790496, '2022-01-06 06:02:05', 'Bad Luck Banging or Loony Porn', '2021-04-16', '/wP28rWRjcD1994uSLXAg0MZmUK7.jpg', 'Emi, a school teacher, finds her career and reputation under threat after a personal sex tape is leaked on the Internet. Forced to meet the parents demanding her dismissal, Emi refuses to surrender to their pressure.'),
(795607, '2022-01-06 06:02:04', 'Green Snake', '2021-07-23', '/xoTxAxzloyUvDK2DKhGb9iSyBRe.jpg', 'While trying to free her sister from Fahai\'s clutches, Xiao Qing/Verta winds up in a dystopian city and meets a mysterious man who can\'t recall his past lives.  The sequel to Light Chaser Animation\'s film about the legend of the White Snake.'),
(795813, '2022-01-06 06:02:05', 'I\'m Your Man', '2021-07-01', '/jqBtRpHKjxXR5eSswPMKfo0wOAI.jpg', 'Alma is a scientist at Berlin\'s famous Pergamon Museum. In order to obtain research funds for her studies, she accepts an offer to participate in an extraordinary experiment. For three weeks, she must live with a humanoid robot with artificial intelligence designed to allow it to morph into that of her ideal life partner. Enter Tom, a machine in human form, created to make her happy.'),
(796515, '2022-01-06 06:02:05', 'Mahishasuramardini', '2022-01-06', NULL, 'the film has been conceptualized as an apology letter to women from all sections of society, who have faced discrimination as well as have been victimized by both men and women in the patriarchal system.'),
(797838, '2022-01-06 06:02:05', 'Firebird', '2021-11-25', '/7WS8dSEJa4XiN1aeI1F6Wtu5OmB.jpg', 'At the height of the Cold War, a troubled soldier forms a forbidden love triangle with a daring fighter pilot and his female comrade amid the dangerous surroundings of a Soviet Air Force Base.'),
(800762, '2022-01-06 06:02:05', 'Sensation', '2021-12-31', '/2mnTP90bGvHlqPhbuOWbPgl2CkU.jpg', 'When a lowly postman is inducted into a top-secret superhuman DNA program at a research facility, it\'s revealed that he\'ll be able to receive, control and send information based on the senses of others.'),
(802217, '2022-01-06 06:02:05', '8-Bit Christmas', '2021-11-25', '/vDSasKnGHsRfX0kTAu5rTl0TQzG.jpg', 'In suburban Chicago during the late 1980s, ten-year-old Jake Doyle embarks on a herculean quest to get the latest and greatest video game system for Christmas.'),
(805051, '2022-01-06 06:02:04', 'The Ogglies: Welcome to Smelliville', '2021-01-01', '/2nU5H8XIgtMkJrxsryP6nJuAHQ.jpg', 'The Oggly family arrive at the municipal rubbish dump of Smelliville and must look for a new home, but they never feel really welcome anywhere. They stink and are for most humans just a tad too oggly. When Firebottom, the family dragon, crash-lands on the run-down rubbish tip of the small town of Smelliville, the Ogglies at once feel at home. And it\'s here they want to stay.'),
(805973, '2022-01-06 06:02:05', 'Christmas at the Ranch', '2021-12-01', '/3Hu2NrLq07sZovInAN5wIaAo8xf.jpg', 'When Haley Hollis returns to her family ranch to try and save it from closure, she wasn\'t banking on spending so much time with ranch hand Kate - or falling for her.'),
(807196, '2022-01-06 06:02:04', 'Boiling Point', '2021-11-19', '/hdx7y952Mn92wyZZnnkLQwou671.jpg', 'A head chef balances multiple personal and professional crises at a popular restaurant in London.'),
(810407, '2022-01-06 06:02:05', 'Snow Maiden Against Everyone', '2021-12-30', '/jKWV4dDINjvt21feVOu8Q2r1VQC.jpg', 'The main qualities of 45-year-old businessman Yevgeny Vasin are the brilliant mind, thanks to which he became rich, and the disgusting character, which turns the life of the businessman\'s relatives and subordinates into a real hell. On New Year\'s Eve, Vasin knocks down Santa Claus in a car and, instead of providing help, steals a Christmas tree and leaves. Punishment is inevitable. Santa Claus transmits Evgeny\'s soul into the body of his Snow Maiden. Now, in the image of his grandfather\'s helper, Vasin will have to deliver gifts to all those whom he has offended, humiliated or insulted, to look at himself from the outside and check whether his life and the life of his family are similar to the fairy tale that Yevgeny drew for himself.'),
(810693, '2022-01-06 06:02:05', 'Jujutsu Kaisen 0: The Movie', '2021-12-24', '/rcEDPOOOUTLFxLLQJggfLffbofe.jpg', 'Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won\'t leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?'),
(812204, '2022-01-06 06:02:05', 'Rock Dog 2: Rock Around the Park', '2021-06-24', '/uMPJwWDojedB36iowSl3HTLmTjW.jpg', 'When Bodi and his band \'True Blue\' leave Snow Mountain, to tour with pop sensation, Lil\' Foxy, they learn that fame comes at a price.'),
(820722, '2022-01-06 06:02:05', 'The Good Boss', '2021-10-15', '/psjZg80xI2KP7xLZ1qKWwYpFzHU.jpg', 'Awaiting a visit by a committee that could give his company an award for excellence, the owner of an industrial scales manufacturing business tries to resolve any problems from his workers in enough time.'),
(821661, '2022-01-06 06:02:05', 'A Year-End Medley', '2021-12-29', '/2tZb1Aq8TK55GAWuGnosGy9Rmt5.jpg', 'A romantic comedy of a young man and woman that is told in the background of hotel \'Emross\'. It has stories of people who met each other at Hotel Emross during the New Year holidays. Each one has his own memory to relate and create relationships or just going nostalgic.'),
(823425, '2022-01-06 06:02:04', 'National Champions', '2021-12-10', '/vKS83sm6FXsrKU4GAX2O8B3S110.jpg', 'A star quarterback ignites a players’ strike hours before the biggest game of the year in order to fight for fair compensation, equality, and respect for the athletes who put their bodies and health on the line for their schools.'),
(823609, '2022-01-06 06:02:05', 'Monster Family 2', '2021-01-13', '/9OE62lhp5FPNJMfKXodegVLjHUA.jpg', 'To free Baba Yaga and Renfield from the clutches of Monster Hunter Mila Starr, the Wishbone Family once more transforms into a Vampire, Frankenstein\'s Monster, a Mummy and a Werewolf. Aided and abetted by their three pet bats, our Monster Family zooms around the world again to save their friends, make new monstrous acquaintances and finally come to the realization that ‘Nobody’s Perfect’ – even those with flaws can find happiness.'),
(824184, '2022-01-06 06:02:05', 'Three Heroes and The Horse on The Throne', '2021-12-30', '/3AP6umJzswdgPZMiAHmOvnQL8nt.jpg', 'As always, our beloved horse, Julius, is steeped in history. And at the same time he helped the Prince - they accidentally exchanged bodies, of course, not without the help of an old acquaintance - Baba Yaga and a little witchcraft. Now Julius is sitting in the palace and landscaping Kiev, and the Prince plows the field. These are the games of thrones. But this cannot go on for long, the fatherland is in danger! And as always, three heroes get down to business.'),
(825808, '2022-01-06 06:02:05', 'See for Me', '2022-01-07', '/tF8ia7uHqCPQf0ilcJlctJCXgJk.jpg', 'When blind former skier Sophie cat-sits in a secluded mansion, three thieves invade for the hidden safe. Sophie\'s only defense is army veteran Kelly, who she meets on the See For Me app. Kelly helps Sophie defend herself against the invaders and survive.'),
(826241, '2022-01-06 06:02:05', 'La familia perfecta', '2021-12-03', NULL, 'Lucía (Belén Rueda) is a woman for whom leading a model life and taking control of her life is the most important thing. Since she got married, she has focused all of her efforts on caring for her family, until achieving what for her is a perfect family. However, her entire world begins to collapse with the arrival of Sara (Carolina Yuste), the girlfriend of her son; a young girl with great freedom and without mincing words who has a very different family from what Lucia always dreamed of as a political family. Now, Lucia must accept that the perfect family was not exactly what she thought.'),
(826749, '2022-01-06 06:02:05', 'Fortress', '2021-12-17', '/1BqX34aJS5J8PefVnQSfQIEPfkl.jpg', 'The story revolves around a top-secret resort for retired U.S. intelligence officers. A group of criminals led by Balzary breach the compound, hellbent on revenge on Robert, forcing the retired officer and his son to save the day.'),
(831827, '2022-01-06 06:02:05', 'Far From the Tree', '2021-11-24', '/d3dkL8C7gfd8cv5xJLBJ3IG37nY.jpg', 'On an idyllic beach in the Pacific Northwest, curiosity gets the better of a young raccoon whose frustrated parent attempts to keep them both safe.'),
(834027, '2022-01-06 06:02:05', 'Val', '2021-07-23', '/gV2wSIlNMIUxEArKYrTF2NX4tjb.jpg', 'For over 40 years Val Kilmer, one of Hollywood’s most mercurial and/or misunderstood actors has been documenting his own life and craft through film and video. He has amassed thousands of hours of footage, from 16mm home movies made with his brothers, to time spent in iconic roles for blockbuster movies like Top Gun, The Doors, Tombstone, and Batman Forever. This raw, wildly original and unflinching documentary reveals a life lived to extremes and a heart-filled, sometimes hilarious look at what it means to be an artist and a complex man.'),
(838885, '2022-01-06 06:02:05', 'My Brothers and I', '2022-01-05', '/maFsk8sw4yf7RKrq4hBLeGtELDo.jpg', ''),
(851303, '2022-01-06 06:02:04', 'Waiting for Bojangles', '2022-01-05', '/gxTlK2qRWTtvIYqGaZQ2j3CtYD3.jpg', 'In front of their little boy, Camille and Georges dance on their favorite song \"Mr Bojangles\". With them, there is only place for fun and fantasy. The one who shows the way is the mother, an unpredictable wisp. She leads them into a whirlwind of poetry so that the party continues again and again, no matter what happens. Mad love has never lived up to its name so well.'),
(854188, '2022-01-06 06:02:05', 'The Kindred', '2021-12-28', '/xHd6rARprd4woZinkziIntiTSZD.jpg', 'After her father’s suicide, a young mother investigates what led to his death. But when she is haunted by spirits and unearths an unsolved mystery from 30 years ago, she discovers a dark family history that could prove deadly for her child.'),
(860720, '2022-01-06 06:02:04', 'El refugio', '2021-11-26', '/3jmhVjFWTCiOCY4x3snv1yVppid.jpg', 'An actor in low hours and a young interpreter who threatens to displace the former thanks to the tricks of their agent; the owner of the high mountain hotel and her estranged sister, creator of a new and unique discipline that mixes yoga and fengshui; a group of children wanting to have fun, but also to discover hidden secrets; a taciturn bellboy who sees everything; and a tremendous storm that will leave everyone isolated just before Christmas. A weekend in which everything can happen, and in which everything will happen.'),
(881211, '2022-01-06 06:02:05', 'Snoopy Presents: For Auld Lang Syne', '2021-12-09', '/7tJSulnvERJn6R9Ih2C2Uvpm8zy.jpg', 'After finding out her grandmother won\'t be visiting for Christmas, Lucy decides to cheer herself up by throwing the ultimate New Year\'s Eve party. Meanwhile, Charlie Brown tries to fulfill one of his resolutions before the clock strikes midnight.'),
(884571, '2022-01-06 06:02:05', 'Quatro Amigas Numa Fria', '2022-01-06', NULL, ''),
(887767, '2022-01-06 06:02:05', 'Last Shoot Out', '2021-12-03', '/upOi9aVqPPky7Ba4GsiyFdjc82I.jpg', 'Soon after a newlywed learns that her husband had her father shot down, she flees from the Callahan ranch in fear. She\'s rescued by a gunman who safeguards her at a remote outpost as he staves off her husband\'s attempts to reclaim his bride.'),
(889814, '2022-01-06 06:02:05', 'Road to Perth', '2022-01-07', '/vNv7HZ4ACpDlpMs8khZsr2ih211.jpg', 'Rejected after a marriage proposal, Alex finds himself alone on a journey from Los Angeles to Melbourne, Australia, on what was supposed to be a happy vacation with his new fiancée. Stuck in a mild state of shock, Alex crosses paths with Ronnie - a woman on an adventure of her own - and together they take a grand road trip across Australia\'s Nullarbor Plain, on their way to Perth.'),
(891691, '2022-01-06 06:02:05', 'Джигалоу', '2022-01-06', NULL, 'Moscow is a city of women! Both fatal, greedy beauties and naive, hungry for relationships, materially prosperous virgins live here in huge numbers. It is the latter that Vova and Edik use for their commercial purposes. Once the guys meet Olya and Rita, the widow and daughter of a recently deceased large businessman. The girls are rich and naive, their hearts and wallets are open. Edik and Vova are in anticipation of enrichment. But unexpected events make the heroes think that things are not so simple with Olya and Rita.'),
(891943, '2022-01-06 06:02:05', 'The Crime', '2022-01-05', NULL, 'The Crime is Egyptian Film'),
(892835, '2022-01-06 06:02:05', 'Book of Love', '2022-01-06', '/pUJsIkcJ9h3nL3l3KF8oDSOkF7O.jpg', 'Young, uptight English writer Henry’s novel is a resolute failure. He is delighted to find out his book is a surprise hit in Mexico but when he is invited there to promote it, he soon discovers why: his Spanish translator Maria has rewritten his dull book as an erotic novel. Henry is furious, and even more so when his publisher insists he and Maria conduct a book tour across Mexico together. Opposites attract and the chemistry between the couple ensures sparks fly.'),
(893297, '2022-01-06 06:02:05', 'American Sicario', '2021-12-10', '/wcJ0H0jDF9U5NFNq8VFcBcqZ6B5.jpg', 'The story of the rise and fall of the first American-born drug lord in Mexico, this tale of power, money, greed and betrayal amongst rival members of the drug cartels finds American gangster Erik Vasquez scheming to become the top dog in the Mexican underworld, only to find himself making enemies out of both the powerful cartels and his own allies.'),
(893770, '2022-01-06 06:02:05', 'Uma Piscina', '2022-01-03', NULL, ''),
(894085, '2022-01-06 06:02:05', 'The Perfect Couple', '2022-01-06', NULL, 'A love story between Kheow, a rowdy Southern boy and Wan, a sweet Northern girl. Their parents scheme a matchmaking by asking them to sell a deserted house in Chiangmai together, but the horrid condition of the house makes this mission nearly impossible. The boy and girl also face the language barrier as they speak different dialects. They also need to find a new job when their meager pocket money is running out. Wan gets a job at Tak Food Center while Kheow earns a position at Mom Thanaddeak Restaurant. They also meet Rew, a real estate businessman, and Prae a chic girl who make Kheow and Wan’s lives even more complicated.'),
(894431, '2022-01-06 06:02:05', 'Rosy', '2022-01-05', NULL, ''),
(898592, '2022-01-06 06:02:05', 'Aay Khuku Aay', '2022-01-06', '/tgFDiPj77QDx6tPhaNUiU7qQaLi.jpg', '\'Aay Khuku Aay\' tells the story of a rural father in the vicinity of Bolpur, W.B. who takes his girl to her wedding. Then?'),
(899251, '2022-01-06 06:02:05', 'Bus Om Bebek', '2022-01-06', NULL, 'Om Bebek who wants to retire as a school bus driver. He and the bus driver, Paman Gembul, want to take the children to school. It turns out that in the middle of the trip, Om Duck\'s bus was hijacked by a kidnapper and the fate of the children on the bus was threatened'),
(899382, '2022-01-06 06:02:05', 'Christmas is Canceled', '2021-12-16', '/uVflhRHoW3ttVs6KxI7BFVZLBBu.jpg', 'Emma\'s father and her high school frenemy start dating so she embarks on a mission to break up the happy couple.'),
(900114, '2022-01-06 06:02:05', 'Shane', '2022-01-06', '/fHkR562Xvs8rM1UMpFv7RRPzABV.jpg', 'For a guy who grew up thinking only of Australian Rules football, it’s almost an accident that Shane Warne became the greatest cricketer of a generation, and one of the greats of all time. Mastering the difficult art of spin bowling after being kicked out of football for not being a good enough player proved a pivotal choice for 19 year old Shane – declared unfit and fat, he transformed himself.  When success came, so did fame and adulation, money and prestige but a betting scandal, drugs scandal, and affairs that cost him his marriage, threatened his career. From the lows of a 12 month ban he rebuilt his cricket, his career, and his reputation as one of the most ferocious competitors on the planet, admired and revered by millions.'),
(903745, '2022-01-06 06:02:05', 'Bolschoi Ballett: Die Tochter des Pharaos', '2022-01-05', '/exr5Yd3gN68Cq0HXeivWfJe3Lgi.jpg', 'Petipa\'s first spectacular ballet was spiritedly transformed by Pierre Lacotte and is a remarkable epic. It is reminiscent of ancient Egypt through great backdrops and choreographies.'),
(911071, '2022-01-06 06:02:05', 'Tú eres mi problema', '2021-12-16', '/di8q2n88q8BcYWm6Iestdu4ZQcI.jpg', ''),
(911622, '2022-01-06 06:02:05', 'For Zeko', '2022-01-05', '/dwn9ecgp9JMQhpfZreeYDfMc7fl.jpg', 'The story follows a girl who lives in an impoverished  neighborhood, who meets a young man and they run into many adventures and paradoxes.'),
(916351, '2022-01-06 06:02:05', 'Payé', '2022-01-06', NULL, ''),
(917134, '2022-01-06 06:02:05', 'Mai 68 au masculin', '2022-01-05', NULL, ''),
(917136, '2022-01-06 06:02:05', 'HK, la plume et l\'espoir', '2022-01-05', NULL, ''),
(917137, '2022-01-06 06:02:05', 'Make Me a Man', '2022-01-05', NULL, ''),
(920143, '2022-01-06 06:02:04', 'El Paseo 6', '2021-12-25', NULL, 'The last year High School excursion is the walk where anything can happen, but the last year High School excursion with the parents, that is the last straw. And since Álvaro Castaño knows that security is better than the police, he decides to travel with his family to watch over his daughter Sarita, however, his mother-in-law, Raquel, is not willing to allow it and also embarks in the plan . On the paradisiacal beaches of San Andrés, Álvaro Castaño will become Sara\'s nightmare and the sensation for the excursion, while his sexy mother-in-law of him will be the one to steal the show. El Paseo 6, the last yeat High School excursion, because the luck of the grandmother, the High School girls wish it.'),
(920235, '2022-01-06 06:02:05', 'Dhimal', '2022-01-06', NULL, 'Dhimal, a scheduled tribe of North Bengal, is debarred by the British Empire.'),
(920912, '2022-01-06 06:02:05', 'Embrace Again', '2022-01-06', NULL, 'From the director of FINDING MR RIGHT comes a series of interconnected stories set against the backdrop of the early days of the pandemic. Here, individual souls realize the world is changing, sometimes yielding heartbreak, sometimes yielding happiness, always leading to a deeper understanding of their fellow human beings. From finding love, to connecting through music, heroes emerge, each contributing in small ways to a very new world around them, however dangerous.');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `userId` int(11) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
  `username` varchar(16) NOT NULL,
  `password` varchar(8) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`userId`, `timestamp`, `username`, `password`) VALUES
(1, '2022-01-06 02:56:24', 'user1', 'pass1');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `favorites`
--
ALTER TABLE `favorites`
  ADD PRIMARY KEY (`favoriteId`),
  ADD UNIQUE KEY `uq_movieId_userId` (`movieId`,`userId`) USING BTREE,
  ADD KEY `movieId` (`movieId`),
  ADD KEY `userId` (`userId`);

--
-- Indexes for table `movies`
--
ALTER TABLE `movies`
  ADD PRIMARY KEY (`movieId`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`userId`),
  ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `favorites`
--
ALTER TABLE `favorites`
  MODIFY `favoriteId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `userId` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `favorites`
--
ALTER TABLE `favorites`
  ADD CONSTRAINT `favorites_ibfk_1` FOREIGN KEY (`movieId`) REFERENCES `movies` (`movieId`),
  ADD CONSTRAINT `favorites_ibfk_2` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
